version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 15
    groups:
      fiks-deps:
        patterns:
          - "KS.Fiks*"
        update-types:
          - "minor"
          - "patch"
      other-deps:
        patterns:
          - "*"
        exclude-patterns:
          - "KS.Fiks*"
        update-types:
          - "minor"
          - "patch"
